import Head from "next/head";
import cv from "./cv.json";

interface workCardProps {
  name: string;
  location: string;
  position: string;
  date: string;
  activities: string[];
}

const WorkCard = (props: workCardProps) => (
  <div className="my-5 card">
    <h3>
      <span className="font-bold text-xl">{props.name}</span>
    </h3>

    <p className="text-sm">{props.position}</p>

    <p>
      {props.location}, {props.date}
    </p>
  </div>
);

interface educationCardProps {
  name: string;
  location: string;
  degree: string;
  date: string;
  description?: string;
}

const EducationCard = (props: educationCardProps) => (
  <div className="my-5 card">
    <h3>
      <span className="font-bold text-xl">{props.name}</span>
    </h3>

    <p className="text-sm">{props.degree}</p>

    <p>
      {props.location}, {props.date}
    </p>
  </div>
);

const Home = () => (
  <div>
    <Head>
      <title>Portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <div className="justify-center my-10">
        <h1 className="text-6xl mb-5">Hi, I am Simon</h1>

        <p>
          Lorem ipsum Lorem ipsum dolor sit amet, consectetur adipiscing elit,
          sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </p>
      </div>

      <div className="mt-10">
        <h2 className="font-bold text-xl">Working experience</h2>
        {cv.work.map((item) => (
          <WorkCard key={item.name} {...item} />
        ))}
      </div>

      <div className="mt-10">
        <h2 className="font-bold text-xl">Education</h2>
        {cv.education.map((item) => (
          <EducationCard key={item.name} {...item} />
        ))}
      </div>
    </main>
  </div>
);

export default Home;
