import Head from "next/head";
import Resume from "../components/resume";

const Link = ({ href, text, color }) => (
  <a
    className={`duration-500 text-black dark:text-white hover:text-[${color}] font-bold`}
    href={href}
  >
    {text}
  </a>
);

const Home = () => {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-white dark:bg-slate-900 text-slate-500 dark:text-slate-400 flex justify-center duration-500">
        <div>
          <div className="my-20">
            <h1 className="text-6xl mb-5 text-black dark:text-white">
              Hi, I am Simon
            </h1>

            <p className="text-xl text-slate-500">
              Studying informatics at{" "}
              <Link href="https://www.in.tum.de/" text="TUM" color="#0065bd" />,
              working student at{" "}
              <Link
                href="https://www.siemens.com"
                text="Siemens"
                color="#00ffb9"
              />
            </p>
          </div>

          <Resume />
        </div>
      </div>
    </>
  );
};

export default Home;
