import Head from "next/head";
import EducationCard from "../components/educationCard";
import WorkCard from "../components/workCard";
import cv from "./cv.json";

const Home = () => (
  <div>
    <Head>
      <title>Portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <div className="justify-center my-10">
        <h1 className="text-6xl mb-5">Hi, I am Simon</h1>

        <p>
          Lorem ipsum Lorem ipsum dolor sit amet, consectetur adipiscing elit,
          sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </p>
      </div>

      <div className="mt-10">
        <h2 className="font-bold text-xl">Working experience</h2>
        {cv.work.map((item) => (
          <WorkCard key={item.name} {...item} />
        ))}
      </div>

      <div className="mt-10">
        <h2 className="font-bold text-xl">Education</h2>
        {cv.education.map((item) => (
          <EducationCard key={item.name} {...item} />
        ))}
      </div>
    </main>
  </div>
);

export default Home;
